export const FETCH_MOVIES_START = "FETCH_MOVIES_START"
export const FETCH_MOVIES_SUCCESS = "FETCH_MOVIES_SUCCESS"
export const FETCH_MOVIES_ERROR = "FETCH_MOVIES_ERROR"
export const UPDATE_FAV_MOVIES = "UPDATE_FAV_MOVIES"
export const FETCH_GENRES = "FETCH_GENRES"



export const CHANGE_FILTERS = "CHANGE_FILTERS"
export const ON_CHANGE_PAGE = "ON_CHANGE_PAGE"